### ISSUE TITLE
Notice: Undefined offset: 1 in C:\xampp\htdocs\classes\_class.func.php on line 171

### ISSUE THREAD

**Issue by muratulashozturk** [iPSWeb/fruit-farm#4]
171th line = 		return $arr_mask[0].".".$arr_mask[1].".".$arr_mask[2].".0";

**Comment by iPSWeb** [comment]
> 171th line = return $arr_mask[0].".".$arr_mask[1].".".$arr_mask[2].".0";

This function (IpCode) has been removed
